setMode -pff
setMode -pff
addConfigDevice  -name "awake_bpm_apr18_2017" -path "C:\Myprojects\CERN_AWAKE_BPM\FPGA_SPARTAN\AWAKE_BPM_Rev2_0\PROM\Apr18_2017"
setSubmode -pffserial
setAttribute -configdevice -attr multibootBpiType -value ""
addDesign -version 0 -name "0"
setAttribute -configdevice -attr compressed -value "FALSE"
setAttribute -configdevice -attr compressed -value "FALSE"
setAttribute -configdevice -attr autoSize -value "FALSE"
setAttribute -configdevice -attr fileFormat -value "mcs"
setAttribute -configdevice -attr fillValue -value "FF"
setAttribute -configdevice -attr swapBit -value "FALSE"
setAttribute -configdevice -attr dir -value "UP"
setAttribute -configdevice -attr multiboot -value "FALSE"
setAttribute -configdevice -attr multiboot -value "FALSE"
setAttribute -configdevice -attr spiSelected -value "FALSE"
setAttribute -configdevice -attr spiSelected -value "FALSE"
addPromDevice -p 1 -size 0 -name xcf08p
addPromDevice -p 2 -size 0 -name xcf32p
setMode -pff
setMode -pff
setSubmode -pffserial
setMode -pff
addDeviceChain -index 0
setMode -pff
setMode -pff
setMode -pff
addDeviceChain -index 0
addDevice -p 1 -file "C:/Myprojects/CERN_AWAKE_BPM/FPGA_SPARTAN/AWAKE_BPM_Rev2_0/PROM/Apr18_2017/download.bit"
setMode -pff
setSubmode -pffserial
generate
setCurrentDesign -version 0
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port auto
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port auto
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port usb21 -baud -1
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
Identify -inferir 
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
identifyMPM 
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setCable -port auto
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port auto
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port auto
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setMode -pff
setMode -pff
setMode -pff
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port auto
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setMode -pff
setMode -pff
setMode -pff
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port auto
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port usb21 -baud -1
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
Identify -inferir 
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
identifyMPM 
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setCable -port auto
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port auto
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port auto
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port auto
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port usb21 -baud -1
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
Identify -inferir 
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
identifyMPM 
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setCable -port auto
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port auto
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port auto
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port auto
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port auto
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setCable -port auto
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -bs
setMode -bs
setMode -bs
setSubmode -pffserial
setMode -pff
setSubmode -pffserial
setMode -pff
setMode -bs
setMode -ss
setMode -sm
setMode -hw140
setMode -spi
setMode -acecf
setMode -acempm
setMode -pff
setMode -pff
saveProjectFile -file "C:\Myprojects\CERN_AWAKE_BPM\FPGA_SPARTAN\AWAKE_BPM_Rev2_0\PROM\Apr12_2017/\auto_project.ipf"
setMode -pff
setMode -bs
setMode -ss
setMode -sm
setMode -hw140
setMode -spi
setMode -acecf
setMode -acempm
setMode -pff
deletePromDevice -position 2
deletePromDevice -position 1
setCurrentDesign -version 0
deleteDevice -position 1
deleteDesign -version 0
setCurrentDesign -version -1
deleteDevice -position 1
deleteDevice -position 1
deleteDevice -position 1
