# Flash programmer parameters file
# Automatically generated by SDK (24/04/2017 10:28:24).

set FLASH_FILE                    "C:/Myprojects/CERN_AWAKE_BPM/FPGA_SPARTAN/AWAKE_BPM_Rev2_0/mb_system/SDK/SW_Design/mb_system_hw_platform/cache/AWAKE_BPM_V1.0.elf.srec"
set FLASH_BASEADDR                0x42000000
set FLASH_PROG_OFFSET             0x00000000
set FLASH_BUSWIDTH                16
set SCRATCH_BASEADDR              0xC0000000
set SCRATCH_LEN                   0x08000000
set TARGET_TYPE                   "MICROBLAZE"
set PROC_INSTANCE                 "microblaze_0"
set EXTRA_COMPILER_FLAGS          "-mxl-barrel-shift -mno-xl-soft-mul -mlittle-endian "
set XMD_CONNECT                   "connect mb mdm  -debugdevice cpunr 1"
set ENDIANNESS                    "LE"
